name: pyml-book
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - certifi=2025.8.3
  - cycler=0.12.1
  - freetype=2.14.1
  - icu=78.2
  - kiwisolver=1.4.7
  - lcms2=2.18
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=21.1.8
  - libdeflate=1.25
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libjpeg-turbo=3.1.2
  - liblapack=3.9.0
  - liblzma=5.8.2
  - libopenblas=0.3.25
  - libpng=1.6.54
  - libsqlite=3.51.2
  - libtiff=4.7.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - ncurses=6.5
  - numpy=1.21.2
  - openjpeg=2.5.4
  - openssl=3.6.1
  - pandas=1.3.2
  - pillow=11.3.0
  - pip=25.2
  - pthread-stubs=0.4
  - pyparsing=3.2.3
  - python=3.9.23
  - python-dateutil=2.9.0.post0
  - python_abi=3.9
  - pytz=2025.2
  - readline=8.3
  - scipy=1.7.0
  - setuptools=59.8.0
  - six=1.17.0
  - tk=8.6.13
  - tornado=6.5.2
  - tzdata=2025c
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zstd=1.5.7
prefix: /opt/homebrew/Caskroom/miniforge/base/envs/pyml-book
